name = "ControlFlow"
uuid = "da1032b5-7410-4fe7-baa6-5cca8121c0cc"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ReTestItems", "Test"]
